# JVM 参数：给 Gradle 守护进程足够内存
org.gradle.jvmargs=-Xmx2560m -Dfile.encoding=UTF-8

# 并行与缓存
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# AndroidX
android.useAndroidX=true
android.nonTransitiveRClass=true

# Kotlin
kotlin.code.style=official
kotlin.incremental=true
